version: '3.8'
services:
  faktory-api:
    container_name: faktory-api
    build:
      context: .
    command:
      - npm run prisma:migrate
      - npm run start:prod
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    networks:
      - faktory-network
    depends_on:
      - postgres-db
  
  postgres-db:
    container_name: postgres-db
    image: postgres:13-alpine
    volumes:
      - database:/var/lib/psqlp/data
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    networks:
      - faktory-network
    ports:
      - 5432:5432
    expose:
      - 5432

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - faktory-network

volumes:
  database:
networks:
  faktory-network:
    driver: bridge